# Generated by Django 4.1 on 2024-09-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_Empleado", models.CharField(max_length=128)),
                ("apellidos", models.CharField(max_length=128)),
                ("correo", models.EmailField(max_length=254)),
                ("estado", models.BooleanField(default=True)),
                ("datos_biometricos", models.CharField(max_length=300)),
                ("celular", models.CharField(max_length=15)),
                ("direccion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Empleo_detalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRambutanGuard.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_entrada", models.TimeField()),
                ("hora_salida", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_Puesto", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=120)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasenia", models.CharField(max_length=128)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRambutanGuard.rol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporte_Mensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("retardos", models.IntegerField()),
                ("salidas_anticipadas", models.IntegerField()),
                ("horas_trabajadas", models.IntegerField()),
                ("horas_extra", models.IntegerField()),
                ("faltas", models.IntegerField()),
                (
                    "empleo_detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRambutanGuard.empleo_detalle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empleo_detalle",
            name="horario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppRambutanGuard.horario",
            ),
        ),
        migrations.AddField(
            model_name="empleo_detalle",
            name="puesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppRambutanGuard.puesto",
            ),
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                (
                    "empleo_detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRambutanGuard.empleo_detalle",
                    ),
                ),
            ],
        ),
    ]
